<style>
    html {
        scroll-behavior: smooth;
    }

    /* ----------------------------------------------
 * Generated by Animista on 2024-9-7 6:33:37
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
 * ----------------------------------------
 * animation slide-bottom
 * ----------------------------------------
 */
    @-webkit-keyframes animate-slide-down {
        0% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
        }

        100% {
            -webkit-transform: translateY(100px);
            transform: translateY(100px);
        }
    }

    @keyframes animate-slide-down {
        0% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
        }

        100% {
            -webkit-transform: translateY(100px);
            transform: translateY(100px);
        }
    }

    .animate-slide-down {
        -webkit-animation: slide-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
        animation: slide-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }

    .custom-textarea {
        box-shadow: none;
        /* Menghilangkan bayangan */
        outline: none;
        /* Menghilangkan garis highlight saat fokus */
        resize: none;
        /* Menonaktifkan resize */
        padding: 10px;
    }

    .custom-textarea:focus {
        outline: none;
        /* Menghilangkan outline saat fokus */
        box-shadow: none;
        /* Hilangkan bayangan saat fokus */
    }
</style>
